### ISSUE TITLE
Action Low Temp Basal set -2147483648%

### ISSUE THREAD

**Issue by komby** [timomer/HAPP#10]
Recommend crazy low temp basal.  On omnipod we can only set temp basal in increments of 5% from -100% (off) and things like -85% -80% etc.  Also increase basal by 15%, or 20% or 100% with steps by 5% 
When it was recommending basals that were semi correct it did recommend a -12% which I cant actually set on omnipod.

![screenshot_2016-03-21-23-00-45](https://cloud.githubusercontent.com/assets/3027079/13956938/e5eb5838-f007-11e5-9975-bd26a1886c51.png)

Profile:
carbAbsorptionRate:20.0
dia:1.5
current_basal:0.15
max_bg:180.0 mgdl
min_bg:100.0 mgdl
target_bg:120.0 mgdl
bg_units:mgdl
isf:150.0 mgdl
carbRatio:25
pump_name:omnipod
aps_mode:open
temp_basal_notification:true
send_bolus_allowed:false
SYSTEM BOLUS_ALLOWED:false
aps_loop:15
aps_algorithm:openaps_oref0_master

Pump:
name: omnipod
basal_mode:Percent of Basal
min_low_basal_duration:30
min_high_basal_duration:30
default_basal_rate:0.15
temp_basal_active:false
temp_basal_rate:null
temp_basal_percent:null
temp_basal_duration:null
temp_basal_duration_left:null

APS Result:
action:Low Temp Basal set -2147483648% for 30mins
reason:Eventual BG 71<100, no temp, setting -0.13U/hr
deviation:0.0
tempSuggested:true
eventualBG:71.0
snoozeBG:99.0
datetime:21 Mar 22:48
rate:0.0
duration:30
basal_adjustemnt:Low
aps_algorithm:openaps_oref0_master
aps_mode:open
current_pump_basal:0.15
aps_loop:15

Stats Result:
datetime:21 Mar 22:59
bolus_iob:0.08717028597317208
iob:0.08717028597317208
cob:0.0
basal:0.15
temp_basal:0.0

Last BG Readings:
date: 21 Mar 22:57 sgv:186.0
date: 21 Mar 22:52 sgv:193.0
date: 21 Mar 22:47 sgv:192.0
date: 21 Mar 22:42 sgv:192.0

**Comment by timomer** [comment]
Hey komby,

Looks like there was an error in my calc for % with pumps that work by PERCENT OF BASAL if a 0 rate Basal was suggested.

Please see the Dev update for a patch (same apk I shared with you in other issue).

Can I confirm, if you have an active basal of 1u and wish to set 0.5u - your would set -50% on the pump?

**Comment by komby** [comment]
Yes the 1u to .5u  on the omnipod it would be -50%

**Comment by timomer** [comment]
Great, this patch should resolve your issue, reopen if not. I'll push this to production next week sometime
