### ISSUE TITLE
Temp Basal Percent calculation of basal * temp amount incorrect

### ISSUE THREAD

**Issue by komby** [timomer/HAPP#11]
When HAPP recommends a temp basal (in percentage mode) it is not accurately calculating the basal.  

See status below.  Basal rate at the time of the temp basal was .2 U/h  

recommend temp basal was 73% increase  

HAPP calculates that as an High Temp of .75U/h

I was expecting a calculation of .2 \* 1.73 = .346 (.35)   as the maximum increased temp basal I can set is 100% which would be .4 U/h

See debug info and screenshot below.

Profile:
carbAbsorptionRate:20.0
dia:2.5
current_basal:0.2
max_bg:140.0 mgdl
min_bg:100.0 mgdl
target_bg:120.0 mgdl
bg_units:mgdl
isf:175.0 mgdl
carbRatio:28
pump_name:omnipod
aps_mode:open
temp_basal_notification:true
send_bolus_allowed:false
SYSTEM BOLUS_ALLOWED:false
aps_loop:15
aps_algorithm:openaps_oref0_master

Pump:
name: omnipod
basal_mode:Percent of Basal
min_low_basal_duration:30
min_high_basal_duration:30
default_basal_rate:0.2
temp_basal_active:true
temp_basal_rate:0.75
temp_basal_percent:73
temp_basal_duration:30
temp_basal_duration_left:29

APS Result:
action:High Temp Basal set 73% for 30mins
reason:Eventual BG 471>140, ajd. req. rate:4.211 to maxSafeBasal:0.750,no temp, setting 0.75U/hr
deviation:0.0
tempSuggested:true
eventualBG:471.0
snoozeBG:471.0
datetime:28 Mar 11:55
rate:0.75
duration:30
basal_adjustemnt:High
aps_algorithm:openaps_oref0_master
aps_mode:open
current_pump_basal:0.2
aps_loop:15

Stats Result:
datetime:28 Mar 11:55
bolus_iob:0.0
iob:0.0
cob:0.0
basal:0.2
temp_basal:0.0

Last BG Readings:
date: 28 Mar 11:52 sgv:327.0
date: 28 Mar 11:47 sgv:323.0
date: 28 Mar 11:42 sgv:320.0
date: 27 Mar 15:27 sgv:183.0
![image](https://cloud.githubusercontent.com/assets/3027079/14087407/bfc396da-f4de-11e5-956e-d4b32678a804.png)

![image](https://cloud.githubusercontent.com/assets/3027079/14087486/18bfd370-f4df-11e5-9b11-56236973eaef.png)

**Comment by timomer** [comment]
Hey,

I may have a misunderstanding of the calc for omnipod TBR - cannot find any documentation on it. 

To confirm my understanding, lets take two examples...
Current Basal: 1u u/hr
Low TBR 0.5 u/hr suggested = -50%
High TBR 1.5 u/hr suggested = 50%

Based on that, the maths I believe should be:
Change = Suggested TBR - Current Basal
% Change = Change / Current Basal \* 100

We then need to cap this to a max negative of -100% and max positive of 100% and finally round to the closest 5.

Does that read correctly?

**Comment by timomer** [comment]
also, to confirm the pump limits you to 100% TBR, so can only double current basal.

ie - basal = 1u, 100% TBR = 2u

sorry for all the questions, I need to adjust APS logic to take into consideration pump limitations

**Comment by komby** [comment]
I did some more research.  It seems there are two options on the Omnipod afterall.  Our pump is currently set to temp basal % mode.  
in percent mode I get the option of 
Increase temp basal in increments of 
5, 10,15, 20, 25, 30,35,40,45,50,55,60,65,70,75, 80,85,90,95   There is no option for an Increase of 100% only 95%

Decrease Temp basal increments are 
5, 10,15, 20, 25, 30,35,40,45,50,55,60,65,70,75, 80,85,90,95,100  the 100% option shuts off basal insulin (temp 0)

Max negative of -100% 
Max Positive of 95%

your calculation looks correct but   basal = 1U  95% TBR would be 1.95 u

Now for the good news,  I never looked and apologize for dragging you down the % road.  Looks like the omnipod also has the option for setting the temp basal in U/h  and has a setting for max temp basal . But for those in % mode I think we have the settings documented in this ticket nicely :)

**Comment by timomer** [comment]
hey, no problem. im happy to support both modes, unless... in U/h mode, can you have a max TBR > 2 \* current basal?

If so, we should support U/h mode only as 2 \* current is very limiting

**Comment by komby** [comment]
temp basal rate as a U/h will support a configurable amount.  There is a separate setting that limits the max basal rate in U/h  the temp basal in u/H will support increments of .05 increments.  The max basal rate setting right now is set to 1U/h  and her normal basal is .2 U/h  it will let me set it from OFF, .05, .1, .15, .2, .25 ...... 1U/h  which seems much more useful to a HAPP setting

**Comment by timomer** [comment]
In U/hr mode, the max basal limit is fixed at 1 U/hr? Or can you set this to be anything you want?

**Comment by komby** [comment]
I can set it to I think anything I want.

I cant select the U/h mode on the omnipod anymore though in HAPP right?

**Comment by timomer** [comment]
for now just pick medtronic - basal percent, that should give you the value you need to support u/hr with omnipod.

As you can set your own limit in U/Hr mode im not going to support omnipod % mode as the max TBR is too low. ill update the profiles now and upload in a bit.

As soon as you can, please add a max TBR value to see if there is any limit imposed.

**Comment by timomer** [comment]
Need to confirm if u/hr mode has a limit then remove HAPP limits for this pump

**Comment by martincohn** [comment]
I was looking for this info just now!  Noticed temp basal was limiting to 200% in HAPP for Omnipod. E.G. my basal is set to .6 U/hr and HAPP would max at 1.2 U/hr. 

I have my max basal set on Omnipod PDM to 3.00 U/hr. Was able to manually set temp basal to max 3.00 U/hr via the PDM. 

Does that give you the info you needed?

**Comment by martincohn** [comment]
Just ran across older info about recommendation to run Omnipod as Medtronic basal absolute. Got a 1.54 U/hr and dialed in into Omnipod PDM. Works just fine. Any updates on HAPP+?  Really interested!

**Comment by timomer** [comment]
Hey @martincohn, yeah U/hr works better for Omnipod.

I have made some great progress with HAPP+, but as a side project, it has been a little neglected due to other life priorities. In May there is an EU dev conference where developers of #wearenotwaiting projects will be discussing plans moving forward and how we can work better together to speed up dev, etc
