### ISSUE TITLE
Omnipod Percent basal suggestions need to be in 5% increments

### ISSUE THREAD

**Issue by komby** [timomer/HAPP#12]
The Omnipod will only allow me to set a temp basal in the Percentage increase or decrease 

The only options allowed are  (increase or decrease) 5%, 10%, 15%......95% 100%  where each step of the percent increase are by 5% 

HAPP is recommending basal settings of 1% which cannot be set on the pod.  

see example below showing a temp basal of 73% .  I can only set 70% or 75%  but not 73%

![image](https://cloud.githubusercontent.com/assets/3027079/14087626/cf1a38a4-f4df-11e5-8cbe-bdc4289ab434.png)

**Comment by timomer** [comment]
will get this fixed in #11
