### ISSUE TITLE
Reason does not respect unit settings

### ISSUE THREAD

**Issue by danpowell88** [timomer/HAPP#16]
Currently I'm set to using mmol/L, the reason text is showing me mg/dL even though the rest of the UI respects the setting and shows mmol/L

**Comment by timomer** [comment]
Hey, reason is provided by the raw OpenAPS code. OpenAPS is not aware of mmol/L units so the conversion is done when passing data for display by HAPP. As reason is a text string its difficult to take out the measurements and convert them - hence why its always shown as mg/dL.

Im very keen to find a way around this, so will keep this open and have a good think!

**Comment by timomer** [comment]
will be resolved in HAPP+ UI redesign
