### ISSUE TITLE
Snooze

### ISSUE THREAD

**Issue by danpowell88** [timomer/HAPP#17]
What is the snooze section showing data for?

I've read through the docco and can't find anything that describes it, perhaps a short addition to the documentation/wiki would be good?

**Comment by timomer** [comment]
Hey,

Yep agree, the reason is that this is the OpenAPS algorithm and I have not documented any of that - but I should provide pointers.

Checkout this: http://openaps.org/reference-design/#algorithms

Review the algorithms section. Please let me know if that answers the question for you?

**Comment by timomer** [comment]
add info to wiki
