### ISSUE TITLE
Integration with NightScout?

### ISSUE THREAD

**Issue by apabari** [timomer/HAPP#18]
Have enabled Integration with NightScout via NS Client; but do not see anywhere to add my NightScout site information.  (xDrip is uploading CGM readings and Calibration Check Readings to NightScout.)

How does one configure HAPP to upload Treatment information to NightScout?

**Comment by timomer** [comment]
Hello,

In HAPP you enable Settings > Integrations > NightScout via NS Client

Pick what you would like to send.

This will send the information to NS Client, NS Client will then upload the data to NightScout.

NS Client can be found here: https://github.com/nightscout/NSClient-Android

**Comment by apabari** [comment]
Thanks!  

Sorry for being daft; but how do I 'install' NS Client?  Or tell if it's working correctly?

None of the information I'm putting into HAPP (Treatment Info) is being uploaded to Nightscout.

**Comment by apabari** [comment]
Hi,

Is there a specific way to install or configure NS Client?  Apologies, I am
not seeing that anywhere.  I have enabled the settings but data is not
being uploaded to Nighscout; the only thing coming through is CGM readings
through xDrip.

Thanks
Andy

**Comment by timomer** [comment]
Hi Andy, have you installed NS Client app? you can download on this page: https://github.com/nightscout/NSClient-Android/releases

**Comment by apabari** [comment]
Hi,

I'm sorry - I did not!  I didn't see the link to the APK until now.
Installed it now!  I just entered a test carb reading, but it keeps saying
'No response on dbAdd"... have I missed a step?

Thanks so much
Andy

**Comment by apabari** [comment]
My apologies -just realized I was running the Master branch of the site,
vs. the Dev site as you previously mentioned.  I am redeploying using Dev
now.

**Comment by timomer** [comment]
No problem, you can get NS Client support here https://gitter.im/nightscout/NSClient-Android

**Comment by apabari** [comment]
Thanks again!

I've tried deploying the DEV branch a few  times, but it fails repeatedly
on Azure... I've read that it happens sometimes, and to keep retrying.  Is
this your experience as well?

Thanks again,
Andy

**Comment by timomer** [comment]
I do not use Azure - have my own server. Best bet is to ask on the NS Client support group or NightScout group
