### ISSUE TITLE
Switch between Percentage Modes

### ISSUE THREAD

**Issue by jessiepusateri** [timomer/HAPP#19]
The OmniPod uses +/- temporary basals but the Medtronic pump just uses the actual percentage of the basal. For example, in a case where my current basal rate is 1U/hr and the algorithm is suggesting that I change it to 2.4U/hr, the app interprets this as 140%. In this case, the OmniPod temporary basal would be entered in as +140% percent but the Medtronic would need to be set to 240% because it works with the percentage of the original basal.

Would it be possible to differentiate the two modes of percentages so that it will display 240% instead of 140%? Thanks!

**Comment by timomer** [comment]
Hey,

HAPP only supports omnipod in u/hr mode as we found % mode was too limiting. 

See this ticket for details: https://github.com/timomer/HAPP/issues/11

You should be able to pick omnipod as your pump in HAPP and set the pump mode to u/hr

Let me know if you don't agree and provide details.

Thanks!

**Comment by timomer** [comment]
Hi, sorry for the confusion - I thought you were discussing the use of the OmniPod.

I dont have access to all pumps, but from feedback I have received is that the "medtronic_percent", "animas" and "omnipod_percent" all calculate % the same.

For example, my expectation is that...
Basal 1u
Suggested TBR is 1.5u
Pump % should be 50%

Is this not correct? For this example what % would you expect?

**Comment by jessiepusateri** [comment]
No worries. In this case, the Pump % for Medtronic would be 150% because it works as a percentage of the original basal.

Another example but for a decrease is:
Basal 1u
Suggested TBR is .4u
Pump % should be 40%

Essentially it's the same calculation as the other pumps except adding 100% at the end.

**Comment by timomer** [comment]
Ok, thanks, sounds like it works the same as the Roche Combo that I have, "hourly basal rate plus TBR percentage"

In HAPP, can you set your pump to "Roche Accu-Chek Spirit Combo" and let me know if the TBR calculated are correct please?

**Comment by jessiepusateri** [comment]
Alright, I just change the pump setting and the percentages are correct. Perfect!

**Comment by timomer** [comment]
Great! ok, ill correct the profile for medtronic pumps in % mode

Anything else please reopen. This update will be in my local Dev branch, prob make master in a few weeks
