### ISSUE TITLE
App Crashes after installation

### ISSUE THREAD

**Issue by oschumac** [timomer/HAPP#2]
Hi Tim,

I tried now different thinks. Using HAPP in Simualtor also on a native 5.1.2 Android. Giving me almost same results. When app crashes on start up it looks like in MainActivity.java an item is not present. I did this workaround ->

```
    //Get IOB and COB only, dont update chart
    public static JSONObject getIOBCOB(Activity a){

        List<Stats> statList = Stats.updateActiveBarChart(a.getBaseContext());
        JSONObject reply = new JSONObject();

        if (statList.size() > 0 ) {
            try {
                reply.put("iob", String.format("%.2f", statList.get(0).iob));
                reply.put("cob", String.format("%.2f", statList.get(0).cob));
            } catch (JSONException e) {
                e.printStackTrace();
            }
            return reply;
        } else {
            try {
                reply.put("iob", String.format("%.2f", 0.00));
                reply.put("cob", String.format("%.2f", 0.00));
            } catch (JSONException e) {
                e.printStackTrace();
            }
            return reply;
        }
```

The APP sending several toasts error getting stats. So do you have an idea whats going on ?

**Comment by timomer** [comment]
Hey, thanks for this.

I am guessing the empty `reply` value was causing the crash in whatever was calling `iobcobActiveFragment.getIOBCOB`

Toast messages, I added this to `updateStats()` as I have been getting random crashes here. https://github.com/timomer/HAPP/blob/master/app/src/main/java/com/hypodiabetic/happ/MainActivity.java#L471

Maybe it could be this line causing the issue: https://github.com/timomer/HAPP/blob/master/app/src/main/java/com/hypodiabetic/happ/MainActivity.java#L484

Can you add a breakpoint to `updateStats()` and find out what line is causing the Exception and therefore the Toast msg?

Please do a pull first to get most recent code
