### ISSUE TITLE
Not getting any readings - what have I done wrong?

### ISSUE THREAD

**Issue by diasigvard** [timomer/HAPP#28]
I've gone through the setting many times, and can't find anyting. In NS Client I get a warning "Unsupported Nightscout version" though. Any clue what this might be? Is this a known issue?

**Comment by timomer** [comment]
You are not using a supported version of nightscout. I know in the past NSClient needed the dev branch of nightscout, you can check here and ask if needed https://gitter.im/nightscout/NSClient-Android

Fyi
With HAPP master, you use eliminate xDrip in NSClient to send readings. Be sure to install xdrip first, then NSClient and HAPP for this to work. Happ dev works much better with NSClient, but is still a little unstable .

Reopen if you get stuck.
