### ISSUE TITLE
Cannot enter decimals in latest dev (Code:47 Name: 1.3.6)

### ISSUE THREAD

**Issue by Rocklita** [timomer/HAPP#33]
I cannot enter a decimal point when entering the numbers for background insulin from pump, insulin sensitivity factor, or Carbohydrate ratio. A work around is to delete the numbers but leave the existing decimal. 
![screenshot_20161127-204823](https://cloud.githubusercontent.com/assets/23317168/20654482/cd910bc0-b4e7-11e6-909b-2b0d749c0057.png)

**Comment by timomer** [comment]
nice spot, fixed in most recent commit.
