### ISSUE TITLE
Support for 640G and Enlite Sensors.

### ISSUE THREAD

**Issue by albertotrg** [timomer/HAPP#39]
It would be nice to add support for the Medtronic 640G insulin pump and the Enlite sensors (Medtronic Continuous Monitoring System). Thanks

**Comment by timomer** [comment]
Hi, 

Does the Medtronic pump profile not meet your needs for the 640g? If not why not?

Enlite sensors - HAPP is an APS system only, CGM data is provided by other apps, for example xDrip and Nightscout (NSClient).

Can you get your CGM data into these apps?

**Comment by albertotrg** [comment]
Hi timoner,

The problem is that we cannot have glucose values on HAPP from the Enlite sensors. I don't know if Enlite is not supported by HAPP or we don't know how to do it.

If HAPP could read the glucose values from Nightscout website, the problem would be solve.

**Comment by timomer** [comment]
Hi,

HAPP does not support any CGM system. CGM data comes from xDrip or Nightscout.

Take a look at the wiki: https://github.com/timomer/HAPP/wiki/System-Integrations

I think NSClient will meet your needs.

**Comment by albertotrg** [comment]
Thanks timoner

**Comment by timomer** [comment]
No problem, if you get stuck just ask in gitter. also let me know if more info would be helpful in the wiki
