### ISSUE TITLE
"User preferences missing" after entering all settings - more verbose logs?

### ISSUE THREAD

**Issue by StephenBrown2** [timomer/HAPP#45]
Hello!

Thank you first and foremost for putting this project together. I wanted to see if I could get it running, and I did for a short while. Once I put in all the info, told xDrip+ to broadcast locally, I got an appropriate temp bolus calculation. The next day, however, it did not appear to be working, though it was receiving xDrip data, it always gives me "User preferences missing, please check all APS & Pump settings are set".

I checked out where it's checking for the settings here: https://github.com/timomer/HAPP/blob/master/app/src/main/java/com/hypodiabetic/happ/services/APSService.java#L189-L194

and it doesn't seem to do anything except if anything is set to null or 0, and return false.

Could this function log which setting(s) is not set so I can see what it's failing on? I'm not terribly familiar with java, as my last experience with it was back in freshman year of college, but I'll see if I can submit a PR after getting what I'm after.

After changing prefsOK to look like this:
```java
    private Boolean prefsOK(){
        if (profile.carbAbsorptionRate.equals(0D)) {
            Log.e(TAG, "User profile preference carbAbsorptionRate missing");
            return false;
        }
        if (profile.dia.equals(0D)) {
            Log.e(TAG, "User profile preference DIA missing");
            return false;
        }
        if (profile.getISF().equals(0D)) {
            Log.e(TAG, "User profile preference ISF missing");
            return false;
        }
        if (profile.getCurrentBasal().equals(0D)) {
            Log.e(TAG, "User profile preference CurrentBasal missing");
            return false;
        }
        if (profile.getCarbRatio().equals(0)) {
            Log.e(TAG, "User profile preference CarbRatio missing");
            return false;
        }
        if (profile.pump_name.equals(Constants.NONE)) {
            Log.e(TAG, "User profile preference pump_name missing");
            return false;
        }
        if (profile.aps_algorithm.equals(Constants.NONE)) {
            Log.e(TAG, "User profile preference aps_algorithm missing");
            return false;
        }
        if (safety.user_max_bolus.equals(0D)) {
            Log.e(TAG, "User safety preference user_max_bolus missing");
            return false;
        }
        if (safety.max_basal.equals(0D)) {
            Log.e(TAG, "User safety preference max_basal missing");
            return false;
        }
        if (safety.max_iob.equals(0D)) {
            Log.e(TAG, "User safety preference max_iob missing");
            return false;
        }
        if (profile.cgm_source.equals("")) {
            Log.e(TAG, "User profile preference cgm_source missing");
            return false;
        }
        return true;
    }
```

I get a compilation error in a completely different file when trying to rebuild:
```
 HAPP/app/src/test/java/com/hypodiabetic/happ/integration/openaps/dev/DetermineBasalAdapterJS_dev_Test.java
     error: constructer DetermineBasalAdapterJS in class DetermineBasalAdapterJS cannot be applied to given types:
     required: ScriptReader, profilefound: ScriptReader
     reason: actual and formal argument lists differ in length
```

But I am able to build the apk anyways.

Currently running with my newly built APK and it seems to be running fine, all settings input and holding, so I haven't needed to check the logs just yet. If it happens again tomorrow I'll try to update here, but the message in the logs would still be helpful to add.

**Comment by timomer** [comment]
Thanks, agree it should be more detailed. Ill leave this open to action.

How are you getting along?

**Comment by StephenBrown2** [comment]
Getting along quite well with the version I compiled myself. So well that I haven't had the issue previously mentioned, so I unfortunately have been a bad contributor and haven't tested my suggested changes. :-/

**Comment by timomer** [comment]
No problem, good to hear, will leave this open for me to add your suggestions

**Comment by StephenBrown2** [comment]
So I can say that it lost the settings again, it was after a sensor change, not sure if that's relevant.

But! I can also say that the changes worked as expected! Hit "Run APS", get generic message, check logcat, fix setting needed, repeat as necessary.

**Comment by StephenBrown2** [comment]
Also, for context, it was the profile settings that got lost, ISF and Carb Ratio. Unfortunately it happened yesterday and I forgot to comment here right away, but that's what I remember.

**Comment by timomer** [comment]
Hey, thanks for that,

Interesting, I don't think the settings are being lost, but there is an issue with the profile builder reloading your profiles. They are saved as a JSON string, if there is an issue with the string a blank profile is loaded.

When you checked ISF and Carb Ratio profiles, where both blank?

I am going to add some more logging to see if we can spot whats happening

**Comment by StephenBrown2** [comment]
Oh gosh, sorry for the lack of reply. Yes, they were zero when I checked.

More logging is (almost) always better!

**Comment by timomer** [comment]
No prob, yep thats the issue then its having an issue reloading them. Ill work on the logging to see what happening

**Comment by timomer** [comment]
changes have been made to the profile builder, please review most recent apk and reopen if needed
