### ISSUE TITLE
Omnipod basal settings

### ISSUE THREAD

**Issue by eurenda** [timomer/HAPP#46]
Not sure but my basal rate 60 minute time slots are not being saved properly, I am unable to input the following example and save it using code:47 name:1.4.1 version using 60 minute increments :

00:00 0.9
02:00 1.5
05:00 0.85
09:00 0.75
12:00 0.85
21:00 1.00

Saves portions of the above and at the 15:00 slot complains that I cannot add an additional 30 minute between this slot and the next

**Comment by timomer** [comment]
Hi, can you give more details where the issue is, I have been able to create the following ok...
00:00 0.9
02:00 1.5
05:00 0.85
09:00 0.75
12:00 0.85
21:00 1.00

![image](https://cloud.githubusercontent.com/assets/5235732/21294218/1fb38f8a-c538-11e6-95f0-0aa9e7e37897.png)

I was also able to then add a 15:00 slot

![image](https://cloud.githubusercontent.com/assets/5235732/21294219/2f25f4b2-c538-11e6-8539-7d2956b98754.png)

Are you able to provide any images of your issue?

**Comment by eurenda** [comment]
Yes, I've attached some images, I think that the first detail shows for me, I can only add sequential slots with 30 or 60 minute time slots:

![screenshot_2016-12-19-12-36-14](https://cloud.githubusercontent.com/assets/1902827/21329096/c3d58d26-c5eb-11e6-8bd5-7ede4c1997ec.png)

This prevents me from replicating a time slots (as in your example) that last more than a single 30 or 60 minute interval, i.e. it forces me to add the example (if I select 60 minute intervals) as:
00:00 ~00:59
01:00 ~01:59
02:00 ~ 23:59 ... etc.

![screenshot_2016-12-19-12-41-12](https://cloud.githubusercontent.com/assets/1902827/21329103/c9866344-c5eb-11e6-8c43-9b784b8ad417.png)

My issue occurs when I try to add the 15:00 time slot from the individual 60 minute entry series.

Hope this helps illustrate better (thanks for your great work Tim).

**Comment by timomer** [comment]
Hey, great thank you for the extra info.

This may answer the issue you are having...
In the last image you have two time slots
-00:00 ~ 00:59
-01:00 ~ 23:59

The value "00:59" is limited by the next time slot start time "01:00". You can change "01:00" to be any value between 01:00 until 23:29. If you change it to "15:00" you will have these as time slots...
-00:00 ~ 00:59
-15:00 ~ 23:59

Now, "00:59" can be changed to any value from 00:59 until 14:59.

Sorry if you are already aware of this, but want to be sure you understand the logic.

**Comment by eurenda** [comment]
Logic understood,  the initial time slot range determines the limit (duh!).  Thanks for explaining it to me Tim - was not aware (thanks your wonderful work on this project)

**Comment by timomer** [comment]
No problem, thank you for the feedback. Wanted the editor to be as simple as possible but with obvious limits so a useable schedule is always created. 
If you think there is any way to make it more clear do let me know
