### ISSUE TITLE
IoB calculation seems off

### ISSUE THREAD

**Issue by eyim** [timomer/HAPP#5]
I inputted 100 carbs with a 8.8 insulin bolus.  DIA is set to 5.

However in looking at the charts it appears that the IoB drops to 0 at the 80 min mark.  Screenshots can be found here

https://www.dropbox.com/sc/daht6bt1x3k677x/AABWZkUGPJPta5S0cCZF0r5Wa

**Comment by timomer** [comment]
Hey, 
The link does not work for me, says "This album is empty"
I have fixed a bug where the predicted IOB was not scaled correctly for the chart, please see most recent commit for fix - if this was not the issue, please reopen
