### ISSUE TITLE
(Basal) Profile issues

### ISSUE THREAD

**Issue by drpmorris** [timomer/HAPP#50]
I've seen some strangeness in the behaviour of the app re basal profile. Sometimes I open the app, and it hasn't run the open aps part for some time, and the default basal shows 0.0u/hr. Trying to manually force the APS by pressing "run aps" the system says it couldn't run as some profile info is missing. When I check my basal profile, all the data is gone. 

Strangely this seems to solve itself eventually.

I wonder if you may also have (and this may be related) 12-24 HR issues in the basal profile entry. It seems I can only enter 12 values - I can't get beyond 12pm (to 23:59). If I try to enter 13:00-13:59 it overwrites the 00:00-00:59 value at the top of the list... The reason it may be related is when I was setting up the profile the first time I hadn't realised it was over writing, saved the profile, but the APS wouldn't run as it said profile info was missing.

Hope that's useful!

**Comment by timomer** [comment]
Hey,

Yes very helpful, thank you. I have also noticed this UI issue where time spans off the screen get reset, this appears to be something to do with the List UI Control. As of yet I have not been able to create the issue while debugging.

When the APS does not run, is this always after a certain time?

**Comment by drpmorris** [comment]
Thanks for the reply.

I thought the APS was stopping at a certain time (13:00 ish... The first
that I couldn't enter into the list...) But now I'm not so sure. It
happened a second time today somewhat later as well.

Cheers

Paul

**Comment by timomer** [comment]
Thanks Paul, going to look at this this week.

**Comment by drpmorris** [comment]
Anecdotally, the profile"seems" to drop out sometimes when switching from
having been looking at xdrip+ to looking at HAPP... Or perhaps if xdrip+
was left open when I turned my phone to standby...

On 2 Feb 2017 08:08, "timomer" <notifications@github.com> wrote:

Thanks Paul, going to look at this this week.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/timomer/HAPP/issues/50#issuecomment-276892811>, or mute
the thread

**Comment by timomer** [comment]
yeah, I think the outcome of this is that its sporadic, I think it may even depend on device load and how Android is releasing memory.

But the fault is with my design, not Android!

**Comment by drpmorris** [comment]
Wish I could offer a hand on the coding, but I only do programming with
pictures (LabVIEW!) Can't cope with actual text based coding!

Good luck getting to the bottom of it!

Paul

**Comment by timomer** [comment]
ha ha, thanks. Yeah, im painfully slow! If you know how to get more hours in a day let me know ;)

**Comment by ToreBj** [comment]
Started with pump a week ago and was set to go with HAPP beforehand . I have been using Xdrip+ for 6 months or so before doing manual injections.
I have experienced what is described here several times, not only the basal profile, but ISF & Carb.rate loss. They all read zero.

Thank you so much for this valuable app, it is a very good tool to follow up on the treatment.

**Comment by timomer** [comment]
Thanks ToreBj for confirming you also have this issue, unfortunately last week was a write off with ATTD, ill get this addressed this week

**Comment by timomer** [comment]
quick update, I have some new code written thats being tested, will share tomorrow if it looks clear of bugs

**Comment by ToreBj** [comment]
Hi, had a closer look at an incident and I'm providing log&debug info in case this could help you on the way solving this. 

Btw No need to apologize :) 

Br Tore

[HAPP debug and log for loss of settings incident.txt](https://github.com/timomer/HAPP/files/796261/HAPP.debug.and.log.for.loss.of.settings.incident.txt)

**Comment by timomer** [comment]
Thanks ToreBj,

I have been using RecyclerView recently for Lists and feel this works better than ListViews so have rewritten and cleaned up the code for a RecyclerView object.

All, please see attached, I have tested this in VM and my phone, the issue with the List redrawing itself incorrectly appears to be gone. Your Profiles will not need to be reentered.

Please provide feedback, thanks 
https://drive.google.com/file/d/0BxE8lMx4AjLiR0RKbXE4bldFSTQ/view?usp=sharing

**Comment by ToreBj** [comment]
Have used  your new version for some time now and I don't see any problems with it.

Still have problems with disappearing settings. I see 2 variants of this. The settings sometimes appear correct when I check them, but must be set again. The other times they are just zero and all basal intervals are gone.

Br Tore

**Comment by timomer** [comment]
Great, thanks for the feedback @ToreBj , as for disappearing settings, as discussed please open a new issue with details + LogCat

Will close this issue now
