### ISSUE TITLE
Retrospective manual insulin / carb input doesn't recalculate 

### ISSUE THREAD

**Issue by Jane49** [timomer/HAPP#52]
Xdrip soldering came apart for about 1.5 hours during which time I bolused, ate and resoldered. 
On manually entering bolus, carb entry and setting the time to the actual time administered RUN APS didn't recaclulate correctly.  The iob and carb appeared to use the entry time rather than the time chosen and saved.   I usually prep, bolus and extend for larger meals.

**Comment by timomer** [comment]
Hi, ill run a test and report back my findings

**Comment by Jane49** [comment]
Many Many Thanks to you and your gitters :)

I also wondered about possibly including the ability to switch between two basal profiles. I need to do this a few times a year for a few weeks when I  am ill as omnipod only allows a 95% increase - I did give ypsomed this information but to no avail.

The other ponder I've had is whether XDRIP and HAPP can/will be ported to android smartphone without the need to carry a phone?????

I think the work you have done for me and many others is fantastic and I cannot express say how grateful I am or tell you the difference it is already making after a few days.

I am very happy to do any open loop testing.

Again, many thanks
Jane







On 19 Feb 2017, at 18:45, timomer <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, ill run a test and report back my findings

**Comment by timomer** [comment]
Thanks Jane!

 switch between two basal profiles. - working on this now
whether XDRIP and HAPP can/will be ported to android smartphone without the need to carry a phone - what do you mean by that!? ;)

**Comment by timomer** [comment]
Hi Jane,

I ran a test with IOB, entered 1u and checked it appeared ok. Then edited and changed the date and again checked that the date of the reading was correct and only part of the Bolus was utilized.

All appeared ok. When you edit a Bolus it deletes the original and adds a new Bolus with the new value or date. I can, therefore, be sure it is not using an "date edited" as only "date created" exists. 

Would you be able to check this again for me and detail the steps that create the issue? 

Thanks, tim

**Comment by Jane49** [comment]
Hi
I have just entered an manual insulin only pre meal Bolus of 3u, saved it.  Gone in again edited it and saved it with the time of approx 20 mins before the current time and saved it.  The first screen still said iob 3.0 ...... hope I'm making sense..... maybe it's me.
Jane

**Comment by timomer** [comment]
I Jane, I have just done the same and IOB updated for me.

Can you take a screen grab for me of before and after entering this, and the treatments page with the events. Finally please copy and paste the output from "Menu > Debug info" so I can see what your DIA, etc is

**Comment by Jane49** [comment]
Hi

Sorry, I don't seem able to be able to replicate it, when/if it recurs I'll grab the screenshots and log.  Maybe it was My method .

Today I've been running at around 200+% .... I deal with this by just percentaging my basal up to cope and then proportionately calculate my Bolus amounts.  Decided to stick without happ ..... I still think it is brilliant!

Lots of thanks
Jane

On 20 Feb 2017, at 18:24, timomer <notifications@github.com<mailto:notifications@github.com>> wrote:


I Jane, I have just done the same and IOB updated for me.

Can you take a screen grab for me of before and after entering this, and the treatments page with the events. Finally please copy and paste the output from "Menu > Debug info" so I can see what your DIA, etc is

**Comment by Jane49** [comment]
Oops ....Should have read ...,. Decided to stick without HAPP today ! ..... big diff....

On 21 Feb 2017, at 17:15, Keith and Jane Bassham <kandj.bassham@hotmail.co.uk<mailto:kandj.bassham@hotmail.co.uk>> wrote:

Hi

Sorry, I don't seem able to be able to replicate it, when/if it recurs I'll grab the screenshots and log.  Maybe it was My method .

Today I've been running at around 200+% .... I deal with this by just percentaging my basal up to cope and then proportionately calculate my Bolus amounts.  Decided to stick without happ ..... I still think it is brilliant!

Lots of thanks
Jane

On 20 Feb 2017, at 18:24, timomer <notifications@github.com<mailto:notifications@github.com>> wrote:


I Jane, I have just done the same and IOB updated for me.

Can you take a screen grab for me of before and after entering this, and the treatments page with the events. Finally please copy and paste the output from "Menu > Debug info" so I can see what your DIA, etc is

**Comment by timomer** [comment]
Hey Jane, sorry we could not pin point the issue.

There may be something happening that the logs and screen grabs can shed some light on.

I am rewriting the code that performs Event entry and will double check what happens when editing Events. 

Please reopen this if you can anymore info

thanks, tim

**Comment by Jane49** [comment]
Hi

Many thanks and will do.

On 24-Feb-17 20:23, timomer wrote:

Hey Jane, sorry we could not pin point the issue.

There may be something happening that the logs and screen grabs can shed some light on.

I am rewriting the code that performs Event entry and will double check what happens when editing Events.

Please reopen this if you can anymore info

thanks, tim
