### ISSUE TITLE
Basal profile editing: Can't add 24 slots

### ISSUE THREAD

**Issue by jamespaulley** [timomer/HAPP#54]
Hi, I can't seem to add 24 slots to the basal profile. It just goes a bit mad and says I can't add any more slots, as well as seeming to delete numbers I've already entered. Any ideas? Thanks!

https://drive.google.com/file/d/1QxXN-Oeal-Kmacs8ADicIFWDpmpQ__Ynag/view?usp=sharing

**Comment by timomer** [comment]
Hey, can you please test with the build listed on this issue: https://github.com/timomer/HAPP/issues/50

**Comment by jamespaulley** [comment]
It seems to be trying to make all the time blocks 30 minutes even though I've selected 60 as the default.

**Comment by jamespaulley** [comment]
I managed to get it to take all the time blocks, but now the app won't open, keeps repeatedly crashing.

**Comment by jamespaulley** [comment]
I think the crash has to do with me removing the setting for max basal.

**Comment by jamespaulley** [comment]
I'm not really sure what to set these to by the way. Just a high number?

**Comment by timomer** [comment]
Can you confirm you are using the build in #50?

Please uninstall and reinstall the app

**Comment by jamespaulley** [comment]
Hi yes I am. The app repeatedly crashed after I deleted my setting for max basal. Reinstalled and now working.

**Comment by timomer** [comment]
thanks james, this build fixed your issues? If not please reopen details what issue you are still having.

many thanks

**Comment by jamespaulley** [comment]
Seems to be working now, many thanks!

**Comment by timomer** [comment]
cool!! I need to pubish this new version
