### ISSUE TITLE
No info on watch face

### ISSUE THREAD

**Issue by jamespaulley** [timomer/HAPP#55]
Hi I can't get the below info to show on the xDrip+ watch face. There isn't an option in xDrip+ Prefs for "Show External Status". There is for "Show Loop Status" and that is enabled but it doesn't seem to do anything. Thanks!

> Active Basal, IOB and COB - this is then displayed on the xDrip Watch Face. Open 'xDrip Prefs' on the Android Wear watch and enable the setting 'Show External Staus'

**Comment by timomer** [comment]
Hi, are you looking at the Prefs on the watch for xDrip+?

**Comment by jamespaulley** [comment]
Yeah.

https://drive.google.com/file/d/0B7btswL3SkCMOG02bDFOT3U2Ujg/view?usp=sharing

**Comment by jamespaulley** [comment]
The watch face looks like this.

![image](https://cloud.githubusercontent.com/assets/26227058/23626823/1e40939a-02a6-11e7-9ece-bbb66981060c.png)

**Comment by timomer** [comment]
I do not use xDrip+ so cannot check, do you not have a pref thats called "Show External Status"? Also please be sure you are running the most recent build.
Also, do you have the setting enabled in HAPP Settings > Integration > xDrip Watch Face

**Comment by timomer** [comment]
fyi - I think that pref "Show Status" is the correct one, please check the setting in HAPP said above

**Comment by jamespaulley** [comment]
The only setting I can see on the xDrip+ settings app ON the watch is "Show Status / Show loop status".

Yes latest beta build.

Yes setting in HAPP is enabled.

So do you use Nightscout instead of xDrip+?

**Comment by timomer** [comment]
I use xDrip instead of xDrip+

Last thing, please reinstall xDrip+ and then HAPP

The order apps install in on Andorid can affect inetr app comms, I know, sounds stupid but it does

**Comment by jamespaulley** [comment]
Ah OK. I think I need to use xDrip+ because I use a LimiTTer device with a Libre sensor.

HAPP was installed after xDrip+ but I'll try it again some time - need them running as they are for today!

Thanks!

**Comment by timomer** [comment]
please reopen if needed
