### ISSUE TITLE
Display all data as mmol/l?

### ISSUE THREAD

**Issue by jamespaulley** [timomer/HAPP#56]
Is it possible to display all data as mmol/l, including the OpenAPS stuff in the status area?

![image](https://cloud.githubusercontent.com/assets/26227058/23626880/61e68136-02a6-11e7-93ac-c094b4aa8c27.png)

**Comment by timomer** [comment]
unfortunately there is no elegant way to do this as that text is the raw output of OpenAPS. But, I am working on a UI redesign that will resolve this issue by not showing this raw text on the main screen 

hope to publish something soon!

**Comment by jamespaulley** [comment]
That new UI sounds great! In the mean time I'll start familiarising myself with mgdl, heh!

**Comment by timomer** [comment]
Happ converts it for you, see eventual and snooze BG on the same screen

**Comment by jamespaulley** [comment]
Cool yes I've been watching those. Not sure what snooze means yet...

**Comment by timomer** [comment]
OpenAPS docs explain this well

**Comment by jamespaulley** [comment]
Cool, I can't work it out but I'll keep trying!
