### ISSUE TITLE
What are the differences between the two algorithms?

### ISSUE THREAD

**Issue by jamespaulley** [timomer/HAPP#57]
Sorry, I've tried searching but can't work it out.

**Comment by jamespaulley** [comment]
Ah I just found this. So it attempts to work out if you're more or less insulin resistant on that day and factors it in to the TBRs?

http://openaps.readthedocs.io/en/latest/docs/walkthrough/phase-4/advanced-features.html#advanced-meal-assist-or-ama

**Comment by timomer** [comment]
Yep, please read the OpanAPS doc  for details. Do note the version in use in HAPP is a good few months out of date

**Comment by jamespaulley** [comment]
Cheers.
