### ISSUE TITLE
Temp Basal Upper Limit Not Passing Value to Suggested Basal Increase

### ISSUE THREAD

**Issue by BrandonBerne** [timomer/HAPP#6]
I've temp max set to 250% as on the tslimg4 you can only increase up to 250% max and the min is dynamic based on current basal. But the recommendation upon being high will indicate set 400% for X minutes as opposed to set 250% for X minutes

-Brandon Berne @ OpenAPS

**Comment by timomer** [comment]
Hi, what value is your Max Basal setting? 250? This is max U/hr (I should add this to the setting description)
This maybe your issue?

**Comment by BrandonBerne** [comment]
There's a few settings I think should help I can grab screen shot next time
I'm high. Likely tomorrow morning.

Please let me know anything else I can do to help you out.

To decode typos from typing on tiny keys, pass through rot13, thrice.

Regards,

Brandon Berne
Brandonberne@gmail.com
8598144805

**Comment by timomer** [comment]
Hey, let me know your "Max Basal" and default basal for that hour, that should be enough for us to workout whats happening.

fyi OpenAPS code only supports U/hr, I have added the ability for the system to suggest a %, hence why settings are U/hr

**Comment by timomer** [comment]
Also, Max IOB

**Comment by timomer** [comment]
fyi - I have now updated the descriptions for the settings to be more clear what values are expected.

**Comment by viktoschi** [comment]
oh that is exactly the same problem that i have... dana R works similar.. max temp basal is limit to 200% and the 200% are based on current basal rate.

**Comment by timomer** [comment]
Same for the Roche Combo, its based on %.

OpenAPS currently only supports U/hr, so Max Basal is U/hr. 
Max Basal OpenAPS can suggest is...
A. The U/hr value of pref Max Basal
B. 4 \* Current Basal

HAPP will then convert this suggested U/hr basal to % increase or decrease of current basal 

Going to close this for now, but happy to reopen for discussion.
