### ISSUE TITLE
Pump and APS profile settings disappear

### ISSUE THREAD

**Issue by ruenightscout** [timomer/HAPP#63]
Hello, I've been using HAPP for a few weeks for open lopping with libre/xdrip+ and all has been great til this morning.  I went to change some pump basal settings and there were none there. Also APS carb ratio and ISF settings had gone too.  I reinstated them manually and used export setting to save them. They disappeared again so I used the import settings to get them back. But whenever I tried to run HAPP it said there were settings missing so after checking I had entries in all the Pump and APS fields several times and it still not working, I unnstalled HAPP and reinstalled  HAPP and manually entered all the settings. It worked for 5 hours then the pump basal and APS carb ratios and ISF  disappeared again.  I used the input settings option which worked but HAPP won't run, says not all settings have entries. If I try to open pump basal settings it says unfortunately HAPP has stopped. I can open APS settings and they are all fine. I would appreciate any help to sort this out and also I'm sorry if this is the wrong place to ask.  I tried asking on facebook CGM in the cloud but no response so not sure where else to ask. I hope it's a simple thing I've done to cause this. Many thanks, Esther

**Comment by ruenightscout** [comment]
Hello, I see this has been raised previously so I'm looking through the history to see if I can find the solution. I also read on your website about HAPP+  and how you say you are not a developer,  you are to me! Thankyou for creating this wonderful app. I hope to get using it again soon as I'm really missing it. Looking forward ton seeing HAPP+ . Thanks again:)

**Comment by ruenightscout** [comment]
I have uninstalled HAPP, deleted the settings file, restarted phone, installed HAPP from #50, re-entered settings. Using it with libre/Sony sw3 for overnight so will need to wait til tonight, hoping it will be working well again:)

**Comment by ruenightscout** [comment]
Have also deleted my question about this from facebook as I now realise this is the appropriate place to ask about it.

**Comment by timomer** [comment]
Hi, yep you are in the right place and thank you for the kind words!

Sounds to me that your profiles are being wiped as there is an issue loading them.

Next time you lose any profile settings, restore from backup and then paste here the text from menu > debug and logcat 

There should be details there saying what has happened

**Comment by ruenightscout** [comment]
Hello Tim, thanks for your reply.  I'm so grateful for people like you who
enable me to monitor my daughter's BG overnight.  I appreciate you are
freely sharing your own work in progress which for the most part works very
well. Hopefully you can iron out the blips!

I got the 'unfortunately HAPP has stopped' message again and when I pressed
Run APS it said it couldn't run because settings were missing. I checked
settings, pump basal rates and APS carb ratios and ISF were gone. This
happened whilst using the version of HAPP from #50 as I saw you directing
people with the same problem to it. It's strange how it worked for a few
weeks totally fine and now this happens. I would love to know what I did to
trigger it! Here's the things you requested, hope they are what you expect.
I know you're doing this in your own time so I don't expect a quick fix.
Thanks for looking into this, Esther


DEBUG INFO


HAPP Version:
Code:  47 Name:1.4.2

Profile:
 carbAbsorptionRate:   30.0
 dia:                  4.0
 current_basal:        0.25
 cgm_source:           xdrip
 max_bg:               169.37 mgdl
 min_bg:               70.27 mgdl
 target_bg:            1801.82 mgdl
 bg_units:             mmol
 isf:                  108.11 mgdl
 carbRatio:            13
 pump_name:            animas
 aps_mode:             open
 temp_basal_notify:    true
 send_bolus_allowed:   false
 SYSTEM_BOLUS_ALLOWED: false
 aps_loop:             5
 aps_algorithm:        openaps_oref0_master

Pump:
 name:                     animas
 basal_mode:               Percent of Basal
 min_low_basal_duration:   30
 min_high_basal_duration:  30
 current_basal_rate:       0.25
 high_temp_extended_bolus: false
 TBR_active:               false
 TBR_rate:                 null
 TBR_percent:              0
 TBR_duration:             null
 TBR_duration_left:        null

APS Result:
 timestamp:        01 Aug 09:52
 action:           Wait and monitor
 reason:           BG data is too old, or clock set incorrectly
 eventualBG:       0.0
 snoozeBG:         0.0
 aps_algorithm:    openaps_oref0_master
 aps_mode:         open
 aps_loop:         5
 TBR_Suggested:    false
 TBR_adjustment:   null
 TBR_rate:         0.0
 TBR_duration:     0

Stats Result:
 timestamp:    01 Aug 09:52
 bolus_iob:    0.0
 iob:          0.0
 cob:          0.0
 basal:        0.25
 temp_basal:   0.0

Safety Result:
 user_max_bolus:       10.0
 hardcoded_Max_Bolus:  15
 user_max_basal:       3.0
 max_daily_basal:      0.65
 current_max_basal:    1.0
 user_max_iob:         6.0

Last BG Readings:
date: 01 Aug 09:38 sgv:100.0
date: 01 Aug 09:30 sgv:113.0
date: 01 Aug 09:17 sgv:110.0
date: 01 Aug 09:13 sgv:107.0
date: 01 Aug 09:09 sgv:107.0



LOGCAT

08-01 09:57:00.199 28110 28110 D Notifications: updateCard: START
08-01 09:57:00.289 28110 28110 D Notifications: updateCard: FINISH
08-01 09:58:00.189 28110 28110 D Notifications: updateCard: START
08-01 09:58:00.269 28110 28110 D Notifications: updateCard: FINISH
08-01 09:59:00.239 28110 28110 D Notifications: updateCard: START
08-01 09:59:00.339 28110 28110 D Notifications: updateCard: FINISH
08-01 09:59:36.019 28110  1346 D FiveMinService: Service Started
08-01 09:59:36.034 28110  1349 D APService: Service Started
08-01 09:59:36.074 28110  1346 D IOB     : calcTempTreatments: START
08-01 09:59:36.099 28110  1346 D IOB     : calcTempTreatments: FINISH,
crunched 0 TempBasal objects for time Tue Aug 01 09:59:36 GMT+01:00 2017
08-01 09:59:36.099 28110  1346 D cob     : cobTotal: START
08-01 09:59:36.169 28110  1349 D DetermineBasal-Master: START
08-01 09:59:36.279 28110  1346 D FiveMinService: New Stat Saved
08-01 09:59:36.314 28110  1346 D IntegrationsManager: Checking Insulin
waiting to be sent, found: 0
08-01 09:59:36.314 28110  1346 D InsulinIntegratNotify:
InsulinIntegrationNotify: START
08-01 09:59:36.329 28110  1346 D InsulinIntegratNotify:
InsulinIntegrationNotify: FINISH
08-01 09:59:36.329 28110 28110 D BackgroundService: onStartCommand Finished
08-01 09:59:36.339 28110  1346 D FiveMinService: Service Finished
08-01 09:59:36.964 28110  1349 D IOB     : calcTempTreatments: START
08-01 09:59:36.964 28110  1349 D IOB     : calcTempTreatments: FINISH,
crunched 0 TempBasal objects for time Tue Aug 01 09:59:36 GMT+01:00 2017
08-01 09:59:36.969 28110  1349 D DetermineBasalAdapterJS: master:
initIobData: [object Object]
08-01 09:59:36.989 28110  1349 D DetermineBasal-Master:
DetermineBasalAdapterJS: FINISH
08-01 09:59:37.059 28110  1349 D APService: Service Finished
08-01 09:59:37.069 28110 28110 D Notifications: updateCard: START
08-01 09:59:37.159 28110 28110 D Notifications: updateCard: FINISH
08-01 10:00:00.169 28110 28110 D Notifications: updateCard: START
08-01 10:00:00.334 28110 28110 D Notifications: updateCard: FINISH
08-01 10:01:00.114 28110 28110 D Notifications: updateCard: START
08-01 10:01:00.159 28110 28110 D Notifications: updateCard: FINISH
08-01 10:02:00.174 28110 28110 D Notifications: updateCard: START
08-01 10:02:00.224 28110 28110 D Notifications: updateCard: FINISH
08-01 10:03:00.189 28110 28110 D Notifications: updateCard: START
08-01 10:03:00.264 28110 28110 D Notifications: updateCard: FINISH
08-01 10:03:06.414 28110  1853 D FiveMinService: Service Started
08-01 10:03:06.419 28110  1854 D APService: Service Started
08-01 10:03:06.449 28110  1853 D IOB     : calcTempTreatments: START
08-01 10:03:06.469 28110  1853 D IOB     : calcTempTreatments: FINISH,
crunched 0 TempBasal objects for time Tue Aug 01 10:03:06 GMT+01:00 2017
08-01 10:03:06.469 28110  1853 D cob     : cobTotal: START
08-01 10:03:06.714 28110  1854 D DetermineBasal-Master: START
08-01 10:03:06.889 28110  1853 D FiveMinService: New Stat Saved
08-01 10:03:06.979 28110  1853 D IntegrationsManager: Checking Insulin
waiting to be sent, found: 0
08-01 10:03:06.979 28110  1853 D InsulinIntegratNotify:
InsulinIntegrationNotify: START
08-01 10:03:07.019 28110  1853 D InsulinIntegratNotify:
InsulinIntegrationNotify: FINISH
08-01 10:03:07.029 28110 28110 D BackgroundService: onStartCommand Finished
08-01 10:03:07.029 28110  1853 D FiveMinService: Service Finished
08-01 10:03:08.234 28110  1854 D IOB     : calcTempTreatments: START
08-01 10:03:08.254 28110  1854 D IOB     : calcTempTreatments: FINISH,
crunched 0 TempBasal objects for time Tue Aug 01 10:03:08 GMT+01:00 2017
08-01 10:03:08.259 28110  1854 D DetermineBasalAdapterJS: master:
initIobData: [object Object]
08-01 10:03:08.304 28110  1854 D DetermineBasal-Master:
DetermineBasalAdapterJS: FINISH
08-01 10:03:08.389 28110  1854 D APService: Service Finished
08-01 10:03:08.424 28110 28110 D Notifications: updateCard: START
08-01 10:03:08.554 28110 28110 D Notifications: updateCard: FINISH
08-01 10:04:00.169 28110 28110 D Notifications: updateCard: START
08-01 10:04:00.209 28110 28110 D Notifications: updateCard: FINISH
08-01 10:05:00.189 28110 28110 D Notifications: updateCard: START
08-01 10:05:00.244 28110 28110 D Notifications: updateCard: FINISH
08-01 10:05:40.804 28110 28110 D MainActivity: Ran BG Update
08-01 10:05:40.814 28110 28110 D MainActivity: Ran Stats Update
08-01 10:05:40.829 28110 28110 D MainActivity: updateRunningTemp: START
08-01 10:05:40.859 28110 28110 D MainActivity: updateRunningTemp: FINISH
08-01 10:05:40.859 28110 28110 D MainActivity: Ran APS Update
08-01 10:05:40.864 28110 28110 D InsulinIntegratNotify:
InsulinIntegrationNotify: START
08-01 10:05:40.869 28110 28110 D InsulinIntegratNotify:
InsulinIntegrationNotify: FINISH
08-01 10:05:40.924 28110  2242 D IOBCOBLineGraph: addfutureValues: START
08-01 10:05:40.929 28110  2242 D IOBCOBLineGraph: addfutureValues: Getting
stats for: Tue Aug 01 10:05:40 GMT+01:00 2017
08-01 10:05:40.929 28110  2242 D IOB     : calcTempTreatments: START
08-01 10:05:40.929 28110  2242 D IOB     : calcTempTreatments: FINISH,
crunched 0 TempBasal objects for time Tue Aug 01 10:05:40 GMT+01:00 2017
08-01 10:05:40.929 28110  2242 D cob     : cobTotal: START
08-01 10:05:40.944 28110 28110 D MainActivity: bgGraph Updated
08-01 10:05:40.974 28110  2242 D IOBCOBLineGraph: addfutureValues: Getting
stats for: Tue Aug 01 10:15:40 GMT+01:00 2017
08-01 10:05:40.974 28110  2242 D IOB     : calcTempTreatments: START
08-01 10:05:40.974 28110  2242 D IOB     : calcTempTreatments: FINISH,
crunched 0 TempBasal objects for time Tue Aug 01 10:15:40 GMT+01:00 2017
08-01 10:05:40.974 28110  2242 D cob     : cobTotal: START
08-01 10:05:41.074 28110  2242 D IOBCOBLineGraph: addfutureValues: Getting
stats for: Tue Aug 01 10:25:40 GMT+01:00 2017
08-01 10:05:41.074 28110  2242 D IOB     : calcTempTreatments: START
08-01 10:05:41.074 28110  2242 D IOB     : calcTempTreatments: FINISH,
crunched 0 TempBasal objects for time Tue Aug 01 10:25:40 GMT+01:00 2017
08-01 10:05:41.074 28110  2242 D cob     : cobTotal: START
08-01 10:05:41.119 28110 28122 I art     : Background sticky concurrent
mark sweep GC freed 104352(4MB) AllocSpace objects, 11(2MB) LOS objects,
36% free, 12MB/19MB, paused 7.826ms total 121.841ms
08-01 10:05:41.144 28110 28110 I Timeline: Timeline: Activity_idle id:
android.os.BinderProxy@ca77415 time:48473731
08-01 10:05:41.159 28110  2242 D IOBCOBLineGraph: addfutureValues: Getting
stats for: Tue Aug 01 10:35:40 GMT+01:00 2017
08-01 10:05:41.159 28110  2242 D IOB     : calcTempTreatments: START
08-01 10:05:41.159 28110  2242 D IOB     : calcTempTreatments: FINISH,
crunched 0 TempBasal objects for time Tue Aug 01 10:35:40 GMT+01:00 2017
08-01 10:05:41.159 28110  2242 D cob     : cobTotal: START
08-01 10:05:41.194 28110  2242 D IOBCOBLineGraph: addfutureValues: Getting
stats for: Tue Aug 01 10:45:40 GMT+01:00 2017
08-01 10:05:41.194 28110  2242 D IOB     : calcTempTreatments: START
08-01 10:05:41.194 28110  2242 D IOB     : calcTempTreatments: FINISH,
crunched 0 TempBasal objects for time Tue Aug 01 10:45:40 GMT+01:00 2017
08-01 10:05:41.194 28110  2242 D cob     : cobTotal: START
08-01 10:05:41.224 28110  2242 D IOBCOBLineGraph: addfutureValues: Getting
stats for: Tue Aug 01 10:55:40 GMT+01:00 2017
08-01 10:05:41.224 28110  2242 D IOB     : calcTempTreatments: START
08-01 10:05:41.224 28110  2242 D IOB     : calcTempTreatments: FINISH,
crunched 0 TempBasal objects for time Tue Aug 01 10:55:40 GMT+01:00 2017
08-01 10:05:41.224 28110  2242 D cob     : cobTotal: START
08-01 10:05:41.259 28110  2242 D IOBCOBLineGraph: addfutureValues: Getting
stats for: Tue Aug 01 11:05:40 GMT+01:00 2017
08-01 10:05:41.259 28110  2242 D IOB     : calcTempTreatments: START
08-01 10:05:41.259 28110  2242 D IOB     : calcTempTreatments: FINISH,
crunched 0 TempBasal objects for time Tue Aug 01 11:05:40 GMT+01:00 2017
08-01 10:05:41.259 28110  2242 D cob     : cobTotal: START
08-01 10:05:41.294 28110  2242 D IOBCOBLineGraph: addfutureValues: Getting
stats for: Tue Aug 01 11:15:40 GMT+01:00 2017
08-01 10:05:41.294 28110  2242 D IOB     : calcTempTreatments: START
08-01 10:05:41.294 28110  2242 D IOB     : calcTempTreatments: FINISH,
crunched 0 TempBasal objects for time Tue Aug 01 11:15:40 GMT+01:00 2017
08-01 10:05:41.294 28110  2242 D cob     : cobTotal: START
08-01 10:05:41.324 28110  2242 D IOBCOBLineGraph: addfutureValues: Getting
stats for: Tue Aug 01 11:25:40 GMT+01:00 2017
08-01 10:05:41.324 28110  2242 D IOB     : calcTempTreatments: START
08-01 10:05:41.324 28110  2242 D IOB     : calcTempTreatments: FINISH,
crunched 0 TempBasal objects for time Tue Aug 01 11:25:40 GMT+01:00 2017
08-01 10:05:41.324 28110  2242 D cob     : cobTotal: START
08-01 10:05:41.359 28110  2242 D IOBCOBLineGraph: addfutureValues: Getting
stats for: Tue Aug 01 11:35:40 GMT+01:00 2017
08-01 10:05:41.359 28110  2242 D IOB     : calcTempTreatments: START
08-01 10:05:41.359 28110  2242 D IOB     : calcTempTreatments: FINISH,
crunched 0 TempBasal objects for time Tue Aug 01 11:35:40 GMT+01:00 2017
08-01 10:05:41.359 28110  2242 D cob     : cobTotal: START
08-01 10:05:41.394 28110  2242 D IOBCOBLineGraph: addfutureValues: Getting
stats for: Tue Aug 01 11:45:40 GMT+01:00 2017
08-01 10:05:41.394 28110  2242 D IOB     : calcTempTreatments: START
08-01 10:05:41.394 28110  2242 D IOB     : calcTempTreatments: FINISH,
crunched 0 TempBasal objects for time Tue Aug 01 11:45:40 GMT+01:00 2017
08-01 10:05:41.394 28110  2242 D cob     : cobTotal: START
08-01 10:05:41.429 28110  2242 D IOBCOBLineGraph: addfutureValues: FINISH
08-01 10:05:41.434 28110  2242 D IOBCOBLineGraph: Updated
08-01 10:05:45.604 28110 28110 D ViewRootImpl: ViewPostImeInputStage
processPointer 0
08-01 10:05:45.719 28110 28110 D ViewRootImpl: ViewPostImeInputStage
processPointer 1
08-01 10:05:47.984 28110 28110 D ViewRootImpl: ViewPostImeInputStage
processPointer 0
08-01 10:05:48.169 28110 28110 D ViewRootImpl: ViewPostImeInputStage
processPointer 1

**Comment by timomer** [comment]
Hey, dont worry, there is a gremlin somewhere to be resolved!

The info you have provided, this was after you tried to run the APS and received "settings were missing"?

Looking at the debug info it says that "BG data is too old, or clock set incorrectly", this was at 09:52, but your last BG reading is at 09:38.

If I remember correctly if your BG is > 15mins old then OpenAPS algorithm will not run as the readings are too old.

As for HAPP crashing, is this when something happens, for example, Run APS, open menu, etc? Can you make it happen or is it random? The reason I ask is that I do not have any new crash reports come in, but, there is a really odd UI bug that causes HAPP to crash and never gets reported. It's only the UI so background process is fine that does all the important stuff.

**Comment by ruenightscout** [comment]
I see what you mean about the 'data is too old' reason rather than the
'settings missing' reasin. Honestly, I thought the message had been
settings missing but maybe the data too old one happened straight after
that but before I copied the info for you. We use the Libre with Sony
Smartwatch attached for overnight cgm. My daughter doesn't wear the watch
during the day so the data too old message appears often and of course
doesn't bother me because I know it's right.  I should really stop HAPP in
the morning but I'm not in the habit, yet! Too busy reminding my daughter
to test her blood and bolus for things otherwise there's no point in me
analysing her data! I will make sure I copy and send you the debug and
other thing again while the reason is 'missing APS and pump settngs'. About
the app crashing, it seems quite random. Happens throughout the day when
I'm using other apps. I don't think I can make it happen but will let you
know if I see any pattern to it. Must be quite difficult to sort out
problems on random people's phones!  Hope you're having a good week, Esther

**Comment by ruenightscout** [comment]
Hello Tim, I have some evidence! Here's the screen (32.png) that says 'user
preferences missing' and also the screen (58.png) with the debug info which
says no temp to cancel but you can see round the edges behind it is the
screen with 'user preferences missing' so the debug info doesn't match the
HAPP main screen. Is there something else I should be doing to get the
right 'reason' on the debug info screen for you?  Interestingly, the pump
and APS settings have reinstated themselves without me doing anything.  See
further screenshots...ignore the high BG, sometimes there's no 'reason',
tonight she forgot to bolus for supper.  No crashing.  If there's more info
or clarification you need, please let me know. Thanks, Esther

![screenshot_2017-08-02-21-28-32](https://user-images.githubusercontent.com/25442477/29216669-52bb9bc4-7ea7-11e7-9bf7-f8139f091f4c.png)

![screenshot_2017-08-02-21-28-58](https://user-images.githubusercontent.com/25442477/29216721-78d2d278-7ea7-11e7-8d8f-78b49734d28b.png)

![screenshot_2017-08-02-22-39-37](https://user-images.githubusercontent.com/25442477/29216748-89567168-7ea7-11e7-8802-80059744940b.png)

![screenshot_2017-08-02-22-43-47](https://user-images.githubusercontent.com/25442477/29216757-8eff0008-7ea7-11e7-94c8-9560ef8b235a.png)







On 2 Aug 2017 19:42, "Esther Rue" <estherjrue@gmail.com> wrote:

I see what you mean about the 'data is too old' reason rather than the
'settings missing' reasin. Honestly, I thought the message had been
settings missing but maybe the data too old one happened straight after
that but before I copied the info for you. We use the Libre with Sony
Smartwatch attached for overnight cgm. My daughter doesn't wear the watch
during the day so the data too old message appears often and of course
doesn't bother me because I know it's right.  I should really stop HAPP in
the morning but I'm not in the habit, yet! Too busy reminding my daughter
to test her blood and bolus for things otherwise there's no point in me
analysing her data! I will make sure I copy and send you the debug and
other thing again while the reason is 'missing APS and pump settngs'. About
the app crashing, it seems quite random. Happens throughout the day when
I'm using other apps. I don't think I can make it happen but will let you
know if I see any pattern to it. Must be quite difficult to sort out
problems on random people's phones!  Hope you're having a good week, Esther

**Comment by timomer** [comment]
Hey Esther, can you send me the images, they are not posted on your last update.

As for app crashing, yep this is the same as what I experience and is completely random. Unfortunately, I have tried to debug this but cannot find any details logged, it appears to be UI related and does not affect the operation of the service that runs in the background. I hope it will be resolved in the HAPP+ rewrite.

**Comment by ruenightscout** [comment]
Ha ha, I have been messaging you from my Gmail app on my phone, didn't realise it was all being posted on git hub! Also wish I could edit my typos,  esp the 'Hell Tim' bit bit I'm sure you know I meant Hello!  In Gmail,  the attachments are showing as sent with the message/post. What should I do to make sure you get them? I'm on holiday so no laptop, just android phone. I would think using a laptop would make a difference? Send from within Gmail or github? App has been working fine last night:) settings all staying where they should be.

**Comment by timomer** [comment]
Hey, thats good to hear.

When you can upload them to GitHub from your laptop would be best, thanks

**Comment by ruenightscout** [comment]
Will do, thanks:)

**Comment by ruenightscout** [comment]
I've added the screenshots to my previous message so you can see what I'm talking about.  HAPP still hasn't lost the settings since I last messaged you.  I wish I knew what it was that triggered the settings to disappear.

**Comment by timomer** [comment]
Hey, thats good to hear.

Underuitnuty the message that a pref is missing is not that helpful as there are a few prefs that are checked, it will be a lot more detailed in HAPP+.

I am going to close for now, but please reopen if the issue pops up again
