### ISSUE TITLE
Error in running APS

### ISSUE THREAD

**Issue by dmchun1986** [timomer/HAPP#68]
Hello~ I have set-up the rig with openaps, and run successfully, but when I m using HAPP , running the APS, it shows There was an error running APS. User preferences missing, please check all APS & Pump settings are set. Could anybody help me

**Comment by timomer** [comment]
Hey, can you give me the output of Menu > Debug Info

**Comment by dmchun1986** [comment]
Thanks for your help, attached with the debug info which I copy from HAPP

HAPP Version:
Code:  48 Name:1.5

Profile:
 carbAbsorptionRate:   0.0
 dia:                  3.0
 current_basal:        0.75
 cgm_source:           nsclient
 max_bg:               3063.09 mgdl
 min_bg:               1261.27 mgdl
 target_bg:            1801.82 mgdl
 bg_units:             mmol
 isf:                  756.76 mgdl
 carbRatio:            7
 pump_name:            medtronic_absolute
 aps_mode:             open
 temp_basal_notify:    true
 send_bolus_allowed:   false
 SYSTEM_BOLUS_ALLOWED: false
 aps_loop:             15
 aps_algorithm:        openaps_oref0_master

Pump:
 name:                     medtronic_absolute
 basal_mode:               Absolute (U/hr)
 min_low_basal_duration:   30
 min_high_basal_duration:  30
 current_basal_rate:       0.75
 high_temp_extended_bolus: false
 TBR_active:               false
 TBR_rate:                 null
 TBR_percent:              0
 TBR_duration:             null
 TBR_duration_left:        null

APS Result:
 APS code has never been ran

Stats Result:
 timestamp:    07 10月 10:03
 bolus_iob:    0.0
 iob:          0.0
 cob:          0.0
 basal:        1.0
 temp_basal:   0.0

Safety Result:
 user_max_bolus:       10.0
 hardcoded_Max_Bolus:  15
 user_max_basal:       5.0
 max_daily_basal:      1.35
 current_max_basal:    3.0
 user_max_iob:         10.0

Last BG Readings:
date: 07 10月 09:05 sgv:78.0
date: 07 10月 09:00 sgv:78.0
date: 07 10月 08:55 sgv:80.0
date: 07 10月 08:50 sgv:80.0
date: 07 10月 08:45 sgv:80.0


2017年10月7日 02:25，"timomer" <notifications@github.com>寫道：

**Comment by timomer** [comment]
Hey,

Your carbAbsorptionRate (Settings > APS Settings > Carb Absorption Rate) is set to 0, this needs a value. 

Please enter a value and reopen if you still have an issue. thanks

**Comment by dmchun1986** [comment]
Its okay, thanks

2017年10月8日 下午5:46，"timomer" <notifications@github.com>寫道：
