### ISSUE TITLE
Temp basal description incorrect for Animas pumps

### ISSUE THREAD

**Issue by sachams** [timomer/HAPP#8]
Animas pumps specify temp basals from -100% (=off) through 0% (=normal) up to +200% (=x3 normal basal). 

This is different to the way percentage basals are currently specified: 0% (=off) through 100% (=normal) up to 300% (=x3 normal basal).

It would be great to add another pump setting ("Percent temp basal, Animas-style")

**Comment by timomer** [comment]
Hey, yep sure. What is the min duration of a high / low temp basal for the Animas?

Ill get a profile created

**Comment by sachams** [comment]
cool. min duration is 30 mins (displayed as "0.5Hr"), max duration is 24Hr.

**Comment by timomer** [comment]
Great thanks, I think thats all i need, will push an update out soon

**Comment by timomer** [comment]
OK, if I have read correctly the animas works the same as the Medtronic set to Percent for TBR.

Checkout the most recent Dev Branch update, I have added a Animas pump profile, check it out and let me know (I can send you an apk if needed?)

Also, do you know if all Animas work like this? Do you pick if they set TBR by % or U/hr?

**Comment by sachams** [comment]
Cool! Just built and installed. 

My xDrip is broken at the moment (the batter wire came off…need to fix) so can’t run HAPP properly but looking at the main screen header that looks right:

Default Basal
0% (1.00U/h) 

To make it even more explicit you could say something like:

Default Basal
Temp basal 0% (1.00U/h) 

But that might be overkill!

I think all animas pump work like this - I’ve got a Vibe now but used to have a 2020 and I think they are the same. You can’t choose - temp basals are always %.

Cheers

**Comment by timomer** [comment]
As thats the Default Basal then no need to say "Temp basal" :)

When TBR is active, it will say that.

Any issues reopen this bug, ill push to master soon

**Comment by sachams** [comment]
👍
