### ISSUE TITLE
Bolus does not allow .05 increments

### ISSUE THREAD

**Issue by komby** [timomer/HAPP#9]
When bolusing on the Omnipod the screen will allow me to enter a insulin amount that is .75 once I confirm the .75 HAPP will recalculate and round it down to .8 and only use .8 in the iob display on screen 
Bolus amounts on omnipod are allowed in .05 increments.

![img_5515](https://cloud.githubusercontent.com/assets/3027079/13956717/0281d87e-f007-11e5-9f5e-ed1d3ee4650e.JPG)
![img_5516](https://cloud.githubusercontent.com/assets/3027079/13956716/027fcc8c-f007-11e5-9ce0-6b245e987f4b.JPG)

**Comment by timomer** [comment]
Hey komby,

I have added Precision Rounding to prefs under Misc settings. Enable this and let me know if that meets your needs? Also cleaned up the UI a little to support this and centralised how rounding is done in HAPP to keep things simple. 

Here is the Dev build: https://drive.google.com/open?id=0BxE8lMx4AjLiNzlKYi1iQ3Q2U00
